#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -z $1 ]]; then
    echo "Usage: get_labels_20bn <20bn storage directory>"
    exit 0
fi

cd $SCRIPTDIR/../data/20bn/
cp *.csv $1

echo "Done!"
