#!/bin/bash


if [[ -z $1 ]]; then
    echo "Usage: dataset2ram <20bn storage directory>"
    exit 0
fi

mkdir -p /dev/shm/20bn-datasets 
echo "created dir" /dev/shm/20bn-datasets

cp -r $1/* /dev/shm/20bn-datasets

echo "Done!"
